# Generated by Django 5.1 on 2024-09-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('eth_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='explore_images/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ExploreImages',
                'verbose_name_plural': 'İlaçlar',
            },
        ),
    ]
