# Generated by Django 5.1 on 2024-09-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('bnb_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avatar', models.ImageField(upload_to='top_users_avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TopUser',
                'verbose_name_plural': 'Top User',
            },
        ),
        migrations.AlterModelOptions(
            name='exploreitem',
            options={'verbose_name': 'ExploreImages', 'verbose_name_plural': 'Explore Images'},
        ),
    ]
