# Generated by Django 5.1 on 2024-09-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcweb', '0004_company_user_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='company',
            name='representative_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_representatives/'),
        ),
    ]
