# Generated by Django 5.1.1 on 2024-09-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcweb', '0005_company_logo_company_representative_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExploreItem',
        ),
        migrations.DeleteModel(
            name='PopularCollection',
        ),
        migrations.DeleteModel(
            name='TopUsers',
        ),
    ]
